"""empty message

Revision ID: 26f350b8b292
Revises: 34e00b3e2ff4
Create Date: 2022-03-31 15:39:01.061353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f350b8b292'
down_revision = '34e00b3e2ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('fullname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'fullname')
    # ### end Alembic commands ###
