"""empty message

Revision ID: 2788587df353
Revises: 26f350b8b292
Create Date: 2022-04-01 18:55:40.414351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2788587df353'
down_revision = '26f350b8b292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'los')
    op.drop_column('projects', 'additional_information')
    op.drop_column('projects', 'skills_offering')
    op.drop_column('projects', 'location')
    op.drop_column('projects', 'custom_los')
    op.drop_column('projects', 'skills_requesting')
    op.drop_column('projects', 'skills')
    op.drop_column('projects', 'advisor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('advisor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('skills_requesting', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('custom_los', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('skills_offering', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('additional_information', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('los', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
