"""empty message

Revision ID: 538f807b1952
Revises: a023e38eef02
Create Date: 2022-04-01 20:59:07.004901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538f807b1952'
down_revision = 'a023e38eef02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'project_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('project_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
