"""empty message

Revision ID: 58fd931f65c9
Revises: fc0dd4fbba3d
Create Date: 2022-03-31 15:04:45.165770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fd931f65c9'
down_revision = 'fc0dd4fbba3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'project_link')
    op.drop_column('user_projects', 'prospectus_link')
    op.drop_column('user_projects', 'prospectus_secondary_file')
    op.drop_column('user_projects', 'cp_courses')
    op.drop_column('user_projects', 'prospectus_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('prospectus_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('cp_courses', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_secondary_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('project_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
