"""empty message

Revision ID: 8ab1bc6bf06d
Revises: a023e38eef02
Create Date: 2022-04-01 21:06:44.257265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab1bc6bf06d'
down_revision = 'a023e38eef02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('project_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'project_link')
    # ### end Alembic commands ###
