"""empty message

Revision ID: de72716d9dc0
Revises: a023e38eef02
Create Date: 2022-03-31 15:00:52.059761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de72716d9dc0'
down_revision = 'a023e38eef02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'prospectus_secondary_file')
    op.drop_column('user_projects', 'cp_courses')
    op.drop_column('user_projects', 'project_link')
    op.drop_column('user_projects', 'prospectus_description')
    op.drop_column('user_projects', 'prospectus_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('prospectus_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('project_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('cp_courses', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_secondary_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
