"""empty message

Revision ID: fc0dd4fbba3d
Revises: de72716d9dc0
Create Date: 2022-03-31 15:03:01.993000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0dd4fbba3d'
down_revision = 'de72716d9dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('project_link', sa.String(), nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_description', sa.String(), nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_link', sa.String(), nullable=True))
    op.add_column('user_projects', sa.Column('prospectus_secondary_file', sa.String(), nullable=True))
    op.add_column('user_projects', sa.Column('cp_courses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'cp_courses')
    op.drop_column('user_projects', 'prospectus_secondary_file')
    op.drop_column('user_projects', 'prospectus_link')
    op.drop_column('user_projects', 'prospectus_description')
    op.drop_column('user_projects', 'project_link')
    # ### end Alembic commands ###
